### ISSUE TITLE
我在哪里可以找到Dbpedia16.rar

### ISSUE THREAD

**Issue by Kiran-38** [pkumod/gAnswer#12]
我想执行我需要Dbpedia16.rar文件的代码。 如帮助文档中所述，但它在哪里？

**Comment by knightmarehs** [comment]
如果你是在找DBpedia16.rar的数据下载地址，可以查看readme中的[快速开始](https://github.com/pkumod/gAnswer#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B)

**Comment by Kiran-38** [comment]
服务器准备好后。 然后我该怎么做才能提问。

**Comment by Kiran-38** [comment]
Hi, I am from india and I want to download Dbpedia16.rar file and when I clicked Click here button in readme page it is taking me to download through baidu web page as i am not familir with chinese language can you please provide that file in english to my email id : malothukiran1@gmail.com 
                                                             Thank you

**Comment by knightmarehs** [comment]
Hi, you can download Dbpedia16.rar using Google Drive, just click [here](https://drive.google.com/open?id=1hmqaftrTo0_qQNRApCuxFXaBx7SosNVy).
After the server ready you can use your browser to ask questions. For example, input this address: http://[ip]:[port]/gSolve/?data={maxAnswerNum:1, maxSparqlNum:2, question:Who is the wife of Donald Trump?}
where [ip] = localhost if you visit on the server computer, and default [port] is 9999.
We will provide a English Help Document as soon as possible.

**Comment by Kiran-38** [comment]
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.String.substring(String.java:1969)
	at lcn.EntityFragmentFields.load(EntityFragmentFields.java:38)
	at qa.Globals.init(Globals.java:72)
	at application.GanswerHttp.main(GanswerHttp.java:71)


I am getting this error may be because of less memory allocation ?

**Comment by knightmarehs** [comment]
Loading the whole data index need 20 GB memory, if you do not have a computer with such memory size you can try the [small data](https://drive.google.com/file/d/11MOHAu00WELxjauuHwDf0KUhEC4841mq/view?usp=sharing).
Notice the small data can not support many questions as the whole data because the data limitation.

**Comment by Kiran-38** [comment]
After the server is started i tried to put this url into my browser
http://localhost:9999/gSolve/?data={maxAnswerNum:1,%20maxSparqlNum:2,%20question:Who%20is%20the%20wife%20of%20Donald%20Trump?}

{"message":"Unkown Exception","status":"500","question":"Who is the wife of Donald Trump?"}
                                                   This is the message that is appearing on the browser web page.


As, I have run from command prompt on my computer this is the Exception that I am getting can you help me please.

[Input:] Who is the wife of Donald Trump?
EntityRecognizer Initial : ok!
--------- entity/type recognition start ---------
Type Check:  wife
Type Check:  Donald
Ent Check: Donald
java.net.UnknownHostException: lookup.dbpedia.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at java.net.Socket.<init>(Socket.java:425)
        at java.net.Socket.<init>(Socket.java:208)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:118)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:683)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:662)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:529)
        at qa.mapping.DBpediaLookup.lookForEntityNames(DBpediaLookup.java:101)
        at qa.mapping.DBpediaLookup.getEntityMappings(DBpediaLookup.java:51)
        at qa.extract.EntityRecognition.getEntityIDsAndNamesByStr(EntityRecognition.java:734)
        at qa.extract.EntityRecognition.process(EntityRecognition.java:330)
        at qa.Query.getMergedQuestionList(Query.java:109)
        at qa.Query.<init>(Query.java:35)
        at qa.GAnswer.getSparqlList(GAnswer.java:42)
        at application.GanswerHandler.handle(GanswerHandler.java:66)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1032)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:258)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:445)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:267)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:224)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)
DBpediaLookup find: [], DBpediaLookup select: []
Type Check:  Trump
Ent Check: Trump
java.net.UnknownHostException: lookup.dbpedia.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at java.net.Socket.<init>(Socket.java:425)
        at java.net.Socket.<init>(Socket.java:208)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:118)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:683)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:662)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:529)
        at qa.mapping.DBpediaLookup.lookForEntityNames(DBpediaLookup.java:101)
        at qa.mapping.DBpediaLookup.getEntityMappings(DBpediaLookup.java:51)
        at qa.extract.EntityRecognition.getEntityIDsAndNamesByStr(EntityRecognition.java:734)
        at qa.extract.EntityRecognition.process(EntityRecognition.java:330)
        at qa.Query.getMergedQuestionList(Query.java:109)
        at qa.Query.<init>(Query.java:35)
        at qa.GAnswer.getSparqlList(GAnswer.java:42)
        at application.GanswerHandler.handle(GanswerHandler.java:66)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1032)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:258)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:445)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:267)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:224)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)
DBpediaLookup find: [], DBpediaLookup select: []
Type Check:  Donald_Trump
Ent Check: Donald_Trump
java.net.UnknownHostException: lookup.dbpedia.org
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at java.net.Socket.<init>(Socket.java:425)
        at java.net.Socket.<init>(Socket.java:208)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:118)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:683)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:662)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:529)
        at qa.mapping.DBpediaLookup.lookForEntityNames(DBpediaLookup.java:101)
        at qa.mapping.DBpediaLookup.getEntityMappings(DBpediaLookup.java:51)
        at qa.extract.EntityRecognition.getEntityIDsAndNamesByStr(EntityRecognition.java:734)
        at qa.extract.EntityRecognition.process(EntityRecognition.java:330)
        at qa.Query.getMergedQuestionList(Query.java:109)
        at qa.Query.<init>(Query.java:35)
        at qa.GAnswer.getSparqlList(GAnswer.java:42)
        at application.GanswerHandler.handle(GanswerHandler.java:66)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1032)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:258)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:445)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:267)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:224)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Thread.java:745)
DBpediaLookup find: [], DBpediaLookup select: []
Type Check:  wife_of_Donald
Type Check:  the_wife_of_Donald
Type Check:  wife_of_Donald_Trump
Ent Check: wife_of_Donald_Trump
Type Check:  the_wife_of_Donald_Trump
Ent Check: the_wife_of_Donald_Trump
------- Result ------
Detect entity mapping: Donald: [
Donald_Lu, Donald_Zec, Donald_Agu, Donald_Gow, Don_Donald, Donald_Rix, Donald_Ker, Donald_Moe, Donald_Don, Donald_Sur, ]
Detect entity mapping: Trump: [
Jay_Trump, Len_Trump, Trump_SoHo, Tone_Trump, Eric_Trump, Fred_Trump, Judd_Trump, Kelly_Trump, First_Trump, Peter_Trump, ]
Detect entity mapping: Donald_Trump: [
Donald_Trump, Donald_Trump_Jr., Donald_Trump,_Jr., Donald_Trump_(song), Donald_Trump_presidential_campaign,_2000, Donald_Trump_presidential_campaign,_2016, Donald_Trump's_The_Art_of_the_Deal:_The_Movie, Planned_presidential_transition_of_Donald_Trump, 2016_Donald_Trump_Chicago_rally_protest, List_of_Donald_Trump_presidential_campaign_primary_endorsements,_2016, ]
Merged: Who is the wife of Donald_Trump ?
Total check time: 864ms
--------- pre entity/type recognition end ---------
step0 [Node Recognition] : 905ms
transQ: Who is the wife of Donald_Trump ?
====StanfordDependencies(566ms)====
 -> be-VBZ (root)[2]
  -> wife-NN (nsubj)[4]
   -> of-IN (prep)[5]
    -> donald_trump-NN (pobj)[6]
   -> the-DT (det)[3]
  -> who-WP (attr)[1]

====MaltDependencies(12ms)====
 -> be-VBZ (root)[2]
  -> wife-NN (nsubj)[4]
   -> of-IN (prep)[5]
    -> donald_trump-NN (pobj)[6]
   -> the-DT (det)[3]
  -> who-WP (attr)[1]

====NameEntityRecognition(19ms)====
Who[1]   ner=null
is[2]   ner=null
the[3]   ner=null
wife[4]   ner=null
of[5]   ner=null
Donald_Trump[6]   ner=null
?[7]   ner=null
Shortest Path between <wife-NN(nsubj)[4]> and <Donald_Trump-NN(pobj)[6]>:
        -<wife-NN(nsubj)[4]>-<of-IN(prep)[5]>-<Donald_Trump-NN(pobj)[6]>-
==========Group Simple Relations=========
=========================================
Check query graph count: 100
Pass single check: 0
Pass final check: 0
TopkJoin time=10
number of rankedSparqls = 0

**Comment by knightmarehs** [comment]
Hi, the entity linking module relies on [DBpedia Lookup](https://wiki.dbpedia.org/lookup/) Web Service, and the query execution relies on [GStore ](http://gstore-pku.com) Web Service.
That is to say you should connect the internet when run the server.
If you do not want to use Web Service, you can download and install them on your local environment.

**Comment by Kiran-38** [comment]
I do have a active internet connection for the server to run. But still why am I facing this problem. Please, I need to run this code. Because I am working on this base paper as part of college project and I have a deadline to submit by this month.

**Comment by nicklin96** [comment]
Hello!
Judging from the exception information, indeed the exception results from lack of memory allocation.
At least 20 GB is necessary for the complete data. Try adding JVM parameters _-Xmx20480m -Xms20480m_ if you have enough memory on your computer.
If you don't, try [small data](https://drive.google.com/file/d/11MOHAu00WELxjauuHwDf0KUhEC4841mq/view?usp=sharing).

**Comment by Kiran-38** [comment]
Thank you, and it is working. Actually when I am connected to LAN it is not working but when I have connected to Mobile hotstop and started the server and asked question it is working. By the way, I wanted to know whether there is any UI page to put request of question because it will be more expressive rather than looking the answer in Command Line/terminal as I have executed it, from command prompt. And also when i tried to use the huge data rather small data i am getting an error of data cache and main exception can anyone tell me what is the meaning of this exception. As I have enough memory to execute it.

**Comment by nicklin96** [comment]
Sorry, at this stage only GanswerHTTP API is available. We have developed a website for demonstration. You can check it [here](http://ganswer.gstore-pku.com/). Hope this will help.

About your exception, it is hard to tell what's going on based on your description. Could you please give more detailed information, like the exception report from back end, the exact memory size of your computer, and whether you use -Xms and -Xmx to allocate enough memory to JVM?

**Comment by Kiran-38** [comment]
1. Total memory: 16GB(RAM)
2. I have used -Xmx to allocate memory to jvm
3. About exception:
                               Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Arrays.java:2694)
        at java.lang.String.<init>(String.java:203)
        at java.io.BufferedReader.readLine(BufferedReader.java:349)
        at java.io.BufferedReader.readLine(BufferedReader.java:382)
        at lcn.EntityFragmentFields.load(EntityFragmentFields.java:51)
        at qa.Globals.init(Globals.java:72)
        at application.GanswerHttp.main(GanswerHttp.java:71)

**Comment by nicklin96** [comment]
For complete data, 20 GB of memory is needed, so 16 GB might not be enough.

**Comment by Kiran-38** [comment]
Hello, I have tried the small data and it is working fine and the answers to the questions are limited though. so, I have a doubt that can we manually give some questions in dbpedia or create a own dataset and when I ask question through http request it gives me response. Is it possible? If yes please do suggest me how can it be done.

**Comment by nicklin96** [comment]
Yes,it can be done. You can create your own dataset based on any RDF data you like. We are working on giving a guide on how to preprocess RDF data. We will finish it as soon as possible.

**Comment by Kiran-38** [comment]
So, if it is done please let me know that process.

**Comment by Kiran-38** [comment]
@nicklin96  Can you please tell me the process how our own data can be created so that if there is any contribution I can do it can you provide me any resource

**Comment by nicklin96** [comment]
Sure! Could you please leave me your email so that I can send you related code and documents.

**Comment by Kiran-38** [comment]
malothukiran0@gmail.com

**Comment by nicklin96** [comment]
Mail sent! Thanks for your concern on gAnswer!

**Comment by Kiran-38** [comment]
Can you please provide me the link to download the triple file in english because it is showing me in chinese which i am not aware of. Thank you

**Comment by knightmarehs** [comment]
Hi, did you try the google drive link we mentioned in [this comment](https://github.com/pkumod/gAnswer/issues/12#issuecomment-466259538)?
I think it should be in English.

**Comment by Kiran-38** [comment]
Yes, it is working fine. But I am having trouble in creating the own data in the existing once. Can you please put one example and create it in the triple, based on that I will create it.

**Comment by Kiran-38** [comment]
Yes, It is working. But I tried to put the details of the triple in my data, in that process of adding I came across YAGO type can you please give some details about that.

**Comment by knightmarehs** [comment]
Hi, did you try the data preprocessing code sent you by @nicklin96 ? It can generate the index files we need from the raw triples.
And if you want to add some YAGO types, it is no need to modify the index files, you can just add them into "data/DBpedia2016/fragments/id_mappings/16yago_types_list.txt".

**Comment by Kiran-38** [comment]
No, not yet. Actually I am having trouble executing the code which he sent me, can you please help me how to do it step by step as i am new to this coding and stuff. It will be a great help. Thank you in advance.

**Comment by Kiran-38** [comment]
Guys, Respond please......

**Comment by Kiran-38** [comment]
1. Hello, I have a problem of retrieving the answer from gstore can you please check the log files and tell me the problem and where am I going wrong. I am attaching a log file please do have a look at eclipse and gstore output.
2. May I know what algorithms are used for ganswer ?

[gstore_install.txt](https://github.com/pkumod/gAnswer/files/3407288/gstore_install.txt)
[eclipse_output_log.txt](https://github.com/pkumod/gAnswer/files/3407290/eclipse_output_log.txt)
