### ISSUE TITLE
您好，按照说明将项目导入eclipse，运行程序时出现以下错误，请您指教。

### ISSUE THREAD

**Issue by yangdand** [pkumod/gAnswer#24]
====== gAnswer2.0 over DBpedia ======
Adding annotator tokenize
Exception in thread "main" java.lang.NoSuchMethodError: edu.stanford.nlp.process.PTBTokenizer.factory(ZZ)Ledu/stanford/nlp/objectbank/TokenizerFactory;
	at edu.stanford.nlp.pipeline.PTBTokenizerAnnotator.<init>(PTBTokenizerAnnotator.java:23)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP$1.create(StanfordCoreNLP.java:360)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:80)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:301)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:145)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:141)
	at nlp.tool.CoreNLP.<init>(CoreNLP.java:34)
	at qa.Globals.init(Globals.java:52)
	at qa.GAnswer.main(GAnswer.java:197)

**Comment by knightmarehs** [comment]
你好，请确认下载了对应分支下的lib文件，并在eclipse项目中将下载的jar包全部加入path。(build path->add external jars ->选择相应jar包）

**Comment by yangdand** [comment]
是我把jar包导错了，谢谢您！
继续向您请教，我的笔记本是8G内存，启动程序会抛出内存溢出的异常，请问您这边有小规模的数据集吗？或者，我该如何把现有的数据集改成小规模的？

**Comment by knightmarehs** [comment]
Hi, please read the [Quick Start](https://github.com/pkumod/gAnswer#quick-start) to find the **smaller dataset**.

**Comment by yangdand** [comment]
您好，这个是英文数据集，请问有中文的吗?

**Comment by knightmarehs** [comment]
中文目前没有提供更小规模的数据集，目前的数据规模16g内存是可以跑的。您可以自行从完整pkubase triples文件抽取小规模子集，通过 generate_fragments/ 中的代码生成相应索引文件。

**Comment by yangdand** [comment]
好的，谢谢您！
