### ISSUE TITLE
程序运行报错: OutOfMemoryError

### ISSUE THREAD

**Issue by iDylanCui** [pkumod/gAnswer#3]
您好！我使用命令: java -jar Ganswer.jar -XX:UseGCOverheadLimit -Xms10240m运行程序报出错误：
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
	at java.lang.StringBuffer.append(StringBuffer.java:367)
	at java.io.BufferedReader.readLine(BufferedReader.java:370)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at lcn.EntityFragmentFields.load(EntityFragmentFields.java:51)
	at qa.Globals.init(Globals.java:72)
	at application.GanswerHttp.main(GanswerHttp.java:33)

我的电脑内存是16G，程序执行时大概用4G多点，扩大java heap space也没有解决问题。请问有什么解决方法吗？谢谢您！

**Comment by YZingao** [comment]
我也遇到了这个问题，也是16G的内存，一开始以为是系统的问题，但是windows和Ubuntu都试了，都是报 java.lang.OutOfMemoryError错误。希望能得到解答。谢谢！

**Comment by knightmarehs** [comment]
很抱歉，经过测试目前完整的DBpedia2016数据索引要求的内存在20G左右（文档里配置要求那里没写清楚orz）。
我们会尽快抽取构建出一个小规模的数据集和对应索引，来供大家在个人电脑上测试使用！

**Comment by iDylanCui** [comment]
好的，十分感谢！

**Comment by YZingao** [comment]
十分感谢作者大大

**Comment by caoyuewen** [comment]
您好，我32g的内存也跑不起来

使用命令：java -jar Ganswer.jar -XX:UseGCOverheadLimit -Xms20480m

报错信息： 
Loading entity fragments ...
Exception in thread "main" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
Exception in thread "DateCache" java.lang.OutOfMemoryError: GC overhead limit exceeded

程序运行时候内存情况：
server@server:/usr/java$ free -h
              total        used        free      shared  buff/cache   available
Mem:            31G        9.0G         11G        1.0M         10G         21G
Swap:          4.0G          0B        4.0G

未运行时内存情况：
server@server:/usr/java$ free -h
              total        used        free      shared  buff/cache   available
Mem:            31G        703M         19G        1.0M         10G         30G
Swap:          4.0G          0B        4.0G

**Comment by knightmarehs** [comment]
> 我的电脑内存是16G，程序执行时大概用4G多点，扩大java heap space也没有解决问题。请问有什么解决方法吗？谢谢您！

> 我也遇到了这个问题，也是16G的内存，一开始以为是系统的问题，但是windows和Ubuntu都试了，都是报 java.lang.OutOfMemoryError错误。希望能得到解答。谢谢！

——————————————————

我们已经构建并上传了小规模数据集供大家进行测试，系统在小规模数据集上运行需要5GB左右内存。
另外，我们修复了部分bug并发布了新的jar包，建议下载最新版本release文件。
