### ISSUE TITLE
在虚拟机上运行Ganswer.jar的时候出现错误

### ISSUE THREAD

**Issue by HAIDIRAO** [pkumod/gAnswer#44]
Loading default properties from tagger edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [3.0 sec].
Adding annotator lemma
Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [1.0 sec].
Loading MaltParser ...ok!
Loading classifier from /home/raobuling/Documents/Ganswer/./././lib/stanford-ner-2012-11-11/classifiers/english.all.3class.distsim.crf.ser.gz ... done [3.9 sec].
/home/raobuling/Documents/Ganswer
NLPatterns.loadPredicateId() : ok!
Warning: DBO not found id count: 34
NLPatterns.loadDboPredicate() : ok!
Number of NL-Patterns-to-predicate mappings = 117885
NLPatterns.size = 31333
Predicate.size = 59347
Warning: Predicates not in DBpedia 2014 count: 1
Jun 20, 2020 8:45:04 PM edu.stanford.nlp.process.PTBLexer next
WARNING: Untokenizable: ိ (U+102D, decimal: 4141)
Jun 20, 2020 8:45:15 PM edu.stanford.nlp.process.PTBLexer next
WARNING: Untokenizable: ‌ (U+200C, decimal: 8204)
NLPatterns.addPredicateAsNLPattern(): ok!
NLPatterns.addHandwriteAsNLPattern(): ok!
NLPatterns.Paradict() : ok!
NLPatterns.buildInvertedIndex(): ok!
Loading entity id ...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:265)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
	at java.util.ArrayList.add(ArrayList.java:462)
	at java.lang.String.split(String.java:2353)
	at java.lang.String.split(String.java:2422)
	at lcn.EntityFragmentFields.load(EntityFragmentFields.java:37)
	at qa.Globals.init(Globals.java:72)
	at application.GanswerHttp.main(GanswerHttp.java:71)

在虚拟机上运行java -jar Ganswer.jar 命令的时候出现这个错误，不知道原因，希望能得到解答，谢谢！

**Comment by nicklin96** [comment]
您好！根据错误信息显示，您运行gAnswer时的栈空间不足。要运行完整的dbpedia数据，需要20G左右的运行内存。您可以用环境变量来给java分配足够的内存。

**Comment by HAIDIRAO** [comment]
您好，我使用了您的小型数据集，发现是可以运行的，但是在将gstore进行本地搭建的时候遇到了一些问题，我找不到您项目中gstore内的数据，希望您能帮助我




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nick Lin"<notifications@github.com&gt;; 
发送时间: 2020年7月6日(星期一) 下午3:09
收件人: "pkumod/gAnswer"<gAnswer@noreply.github.com&gt;; 
抄送: "饶海笛"<772531005@QQ.COM&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pkumod/gAnswer] 在虚拟机上运行Ganswer.jar的时候出现错误 (#44)





 
您好！根据错误信息显示，您运行gAnswer时的栈空间不足。要运行完整的dbpedia数据，需要20G左右的运行内存。您可以用环境变量来给java分配足够的内存。

**Comment by nicklin96** [comment]
你好。我们上传了dbpedia用于建库的nt文件：
https://pan.baidu.com/s/1jQ_jGTniflzoqBhpz5tjnw 提取码  rpev

**Comment by HAIDIRAO** [comment]
谢谢您！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pkumod/gAnswer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 晚上6:46
收件人:&nbsp;"pkumod/gAnswer"<gAnswer@noreply.github.com&gt;;
抄送:&nbsp;"饶海笛"<772531005@QQ.COM&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pkumod/gAnswer] 在虚拟机上运行Ganswer.jar的时候出现错误 (#44)





 
你好。我们上传了dbpedia用于建库的nt文件：
 https://pan.baidu.com/s/1jQ_jGTniflzoqBhpz5tjnw 提取码  rpev
