### ISSUE TITLE
从gAnswer这个类运行项目，报找不到qald6_special.txt文件错误，请问这个文件怎样生成？

### ISSUE THREAD

**Issue by LittleWuWu** [pkumod/gAnswer#45]
java.io.FileNotFoundException: E:\Linyinnian\qald6_special.txt (系统找不到指定的路径。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at utils.FileUtil.readFile(FileUtil.java:14)
	at qa.GAnswer.main(GAnswer.java:202)
另外：暂时未发现中文版的项目与之前的英文版的有何区别，请指教！谢谢！

**Comment by nicklin96** [comment]
您好！这是我们调试时用于存放问题的文本文件，将其替换为您自己的文件即可。格式为一行一个问题。
