### ISSUE TITLE
一个http请求需要花费多少时间呢？ 

### ISSUE THREAD

**Issue by caoyuewen** [pkumod/gAnswer#5]
程序跑起来了之后我调用了一个请求
无论是用postman测试请求还是用程序测试请求 有正确返回结果的 都花费了大约5分钟左右的时间，这是正常的吗，是不是还需要配置什么地方？

**Comment by knightmarehs** [comment]
你好，视问题不同相应时间也不同，一般比较简单的问题可以在几秒钟内回复的，比如"Who is the president of China"。问题很复杂的话会久一些，极端情况也可能要几分钟，你可以试一下在我们的demo网站问同样的问题，看能不能得到返回结果。

**Comment by caoyuewen** [comment]
嗯好的非常感谢
1.我发送了一个这样的请求：
http://【ip】:9999/gSolve/?data={
  "maxAnswerNum":"1",
  "maxSparqlNum":"2",
  "question":"Whos is the wife of Donald Trump?"
}

2.收到的结果是：
{
	"question": "Whos is the wife of Donald Trump?",
	"vars": ["?Whos", "?wife"],
	"sparql": ["select DISTINCT ?Whos ?wife where { \t\t?wife. ?Whos\t\t?wife. } LIMIT 1", "select DISTINCT ?Whos ?wife where { \t\t?wife. ?wife\t\t?Whos. } LIMIT 1"],
	"results": {
		"bindings": []
	},
	"status": "200"
}

3.后台有时候出现如下错误(后台好像又去请求了一个接口http://172.31.222.90:9001/...)然后包超时错误
Check query graph count: 800
Pass single check: 20
Pass final check: 14
TopkJoin time=80
number of rankedSparqls = 14
parameter: ?operation=query&username=root&password=123456&db_name=dbpedia16&format=txt&sparql=select DISTINCT ?Whos ?wife  where { <Donald_Trump>	<spouse>	?wife. ?Whos	<spouse>	?wife. } LIMIT 1
request: http://172.31.222.90:9001/%3Foperation%3Dquery%26username%3Droot%26password%3D123456%26db_name%3Ddbpedia16%26format%3Dtxt%26sparql%3Dselect+DISTINCT+%3FWhos+%3Fwife++where+%7B+%3CDonald_Trump%3E%09%3Cspouse%3E%09%3Fwife.+%3FWhos%09%3Cspouse%3E%09%3Fwife.+%7D+LIMIT+1
error in get request: java.net.ConnectException: Connection timed out (Connection timed out)
java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at jgsc.GstoreConnector.sendGet(GstoreConnector.java:60)
	at jgsc.GstoreConnector.query(GstoreConnector.java:264)
	at qa.GAnswer.getAnswerFromGStore2(GAnswer.java:159)
	at application.GanswerHandler.handle(GanswerHandler.java:89)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1032)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:258)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:445)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:267)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:224)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:748)

**Comment by knightmarehs** [comment]
抱歉，之前的某次提交覆盖了正确的端口号。
现在已经进行了代码更新，请重新下载jar包或者更新代码后自行编译。
另外如果使用浏览器查看返回结果的话，需要在“查看源代码”状态显示，因为结果中包含部分字符可能会被视为html元素而显示错误。
