### ISSUE TITLE
无法得出结果，代码转换python问题

### ISSUE THREAD

**Issue by 2213500360** [pkumod/gAnswer#51]
您好！
我是一名学生，我的导师最近让我将您的gAnswer的java代码用python复现一下，可是我看您的代码调用了许多java的jar包，请问您对如何使用python实现有什么建议吗？还有，我运行了您的gAnswer代码，结果只能得到5个Sparql语句，无法得到最终答案，错误结果如下，感谢！

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1982)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1977)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1976)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1544)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at jgsc.GstoreConnector.sendGet(GstoreConnector.java:67)
	at jgsc.GstoreConnector.query(GstoreConnector.java:264)
	at qa.GAnswer.getAnswerFromGStore2(GAnswer.java:157)
	at qa.GAnswer.main(GAnswer.java:250)
Caused by: java.io.FileNotFoundException: http://dbpedia20.gstore-pku.com:80/%3Foperation%3Dquery%26username%3Droot%26password%3D123456%26db_name%3Ddbpedia16%26format%3Dtxt%26sparql%3Dselect+DISTINCT+%3Fwife++where+%7B+%3CBarack_Obama%3E%09%3Cspouse%3E%09%3Fwife.+%7D+LIMIT+100
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1928)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3152)
	at jgsc.GstoreConnector.sendGet(GstoreConnector.java:64)
	... 3 more

**Comment by nicklin96** [comment]
您好！从log上看gAnswer输出的sparql是对的，但是它从gStore查询结果的时候出现了网络错误
您这个问题比较复杂，您留个邮箱，我把我微信号发给您，我们微信交流可以吗？

**Comment by 2213500360** [comment]
好的，邮箱: 2213500360@qq.com   谢谢
