### ISSUE TITLE
nullpointerror

### ISSUE THREAD

**Issue by xqx1568** [pkumod/gAnswer#57]
在输入问句后产生如下错误，请问与gstore服务有关吗？
应该怎么解决？
[Input:] Which companies are located in California, USA?
EntityRecognizer Initial : ok!
--------- entity/type recognition start ---------
Type Check:  companies
Matched type: Company : 1.0
Matched type: BusCompany : 0.625
Type Check:  California
Ent Check: California
java.lang.NullPointerException
        at qa.mapping.DBpediaLookup.getEntityMappings(DBpediaLookup.java:53)
        at qa.extract.EntityRecognition.getEntityIDsAndNamesByStr(EntityRecognition.java:734)
        at qa.extract.EntityRecognition.process(EntityRecognition.java:330)
        at qa.Query.getMergedQuestionList(Query.java:109)
        at qa.Query.<init>(Query.java:35)
        at qa.GAnswer.getSparqlList(GAnswer.java:42)
        at application.GanswerHandler.handle(GanswerHandler.java:66)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1032)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:258)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:445)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:267)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:224)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.lang.Thread.run(Unknown Source)

**Comment by xqx1568** [comment]
dbpedialookup 修改为https访问
