### ISSUE TITLE
NullPointerException Error 

### ISSUE THREAD

**Issue by raj-ritu** [pkumod/gAnswer#59]
[Input:] What is the Capital of Germany?
EntityRecognizer Initial : ok!
--------- entity/type recognition start ---------
Type Check:  Capital
Type Check:  Germany
Ent Check: Germany
java.lang.NullPointerException
        at qa.mapping.DBpediaLookup.getEntityMappings(DBpediaLookup.java:53)
        at qa.extract.EntityRecognition.getEntityIDsAndNamesByStr(EntityRecognition.java:734)
        at qa.extract.EntityRecognition.process(EntityRecognition.java:330)
        at qa.Query.getMergedQuestionList(Query.java:109)
        at qa.Query.<init>(Query.java:35)
        at qa.GAnswer.getSparqlList(GAnswer.java:42)
        at application.GanswerHandler.handle(GanswerHandler.java:66)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1032)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:258)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:445)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:267)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:224)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
        at java.base/java.lang.Thread.run(Thread.java:834)
        
Any solution for this ?

**Comment by raj-ritu** [comment]
Any  workaround would be greatly appreciated, it's urgent for me.
Thanks

**Comment by raj-ritu** [comment]
Updating the DBpediaLookup link address will resolve the issue.
I have attached the 'DBpediaLookup.java' and 'DBpediaLookup.class' file.

Thank You !!

[DBpediaLookup.zip](https://github.com/pkumod/gAnswer/files/6332570/DBpediaLookup.zip)
